# Generated by Django 4.1.2 on 2022-12-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduleClean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=100)),
                ("location_address", models.CharField(max_length=100)),
                ("location_zip", models.CharField(max_length=100)),
                ("location_city", models.CharField(max_length=100)),
                ("location_country", models.CharField(max_length=100)),
                ("location_state", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_work_requested", models.DateTimeField()),
                ("email", models.EmailField(max_length=100)),
                ("in_progress", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
