# Generated by Django 4.1.2 on 2022-12-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleclean",
            name="date_work_requested",
            field=models.DateTimeField(null=True),
        ),
    ]
