# Generated by Django 4.1.2 on 2022-12-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_app", "0002_alter_scheduleclean_date_work_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleclean",
            name="date_work_requested",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
